export default [

    // Paints
    "lime",
    "slate",
    "purple",
    "distinctive",
    "hue",
    "mint",
    "eight",
    "grey",
    "extraordinary",
    "abundance",
    "tinge",
    "gold",
    "salmon",
    "olive",
    "indubitably",
    "green",
    "orange",
    "muskelmannbraun",
    "noble",
    "violet",
    "peculiarly",
    "tincture",
    "pink",
    "radigan",
    "conagher",
    "brown",
    "bitter",
    "business",
    "rustic",
    "zepheniah",
    "greed",
    "debonair",
    "balaclavas",
    "cream",
    "overalls",
    "spirit",
    "teamwork",
    "waterlogged",

    // Qualities
    "strange",
    "haunted",
    "decorated",
    "genuine",
    "vintage",
    "unusual",
    "community",
    "selfmade",
    "collectors",
    "unique",
    "normal"
];